language: rust

rust:
  - stable
  - nightly

os:
  - osx
  - linux

script:
  - cargo build --verbose
  - cargo run --manifest-path systest/Cargo.toml

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: cargo

notifications:
  email:
    on_success: never
