[package]
name = "systest"
version = "0.1.0"
authors = ["lwshang <lwsh37@gmail.com>"]
edition = "2018"

[dependencies]
q-capi = { path = ".." , features = ["ipc"] }

[build-dependencies]
ctest = "0.2"